Revert "Update builder.yml"
This reverts commit b51cd993c48271d71e2bfc7a53008f85f4df8f98.

diff --git a/.github/workflows/validate-images.yml b/.github/workflows/validate-images.yml
--- a/.github/workflows/validate-images.yml
+++ b/.github/workflows/validate-images.yml
@@ -78,24 +78,23 @@ jobs:
           export DOCKER_CLI_EXPERIMENTAL=enabled
 
           function validate_image() {
-            local image=${1}
-
-            if [[ "$VCN_ORG" =~ ^0x ]]; then
-              vcn_cli="--signerID"
-            else
-              vcn_cli="--org" 
-            fi
-
-            state="$(vcn authenticate ${vcn_cli} $VCN_ORG --output json docker://${image} | jq '.verification.status // 2')"
-
-            if [[ "${state}" != "0" ]]; then
-              echo "Invalid signature!"
-              exit 1
-            fi
-
+                  local image=${1}
+                  
+                  if [[ "$VCN_ORG" =~ ^0x ]]; then
+                          vcn_cli="--signerID"
+                  else
+                          vcn_cli="--org" 
+                  fi
+                  
+                  state="$(vcn authenticate "${vcn_cli}" "$VCN_ORG" --output json docker://"${image}" | jq '.verification.status // 2')"
+                  
+                  if [[ "${state}" != "0" ]]; then
+                          echo "Invalid signature!"
+                          exit 1
+                  fi
           }
 
           for docker_reg in "drypatrick" "ghcr.io/drypatrick"; do
-            docker pull "${docker_reg}/amd64-homeassistant:${{ needs.init.outputs.version }}"
-            validate_image "${docker_reg}/amd64-homeassistant:${{ needs.init.outputs.version }}"
+          docker pull "${docker_reg}/amd64-homeassistant:${{ needs.init.outputs.version }}"
+          validate_image "${docker_reg}/amd64-homeassistant:${{ needs.init.outputs.version }}"
           done
