To Be Deleted

diff --git a/.github/workflows/validate-images.yml b/.github/workflows/validate-images.yml
--- a/.github/workflows/validate-images.yml
+++ b/.github/workflows/validate-images.yml
@@ -33,21 +33,20 @@ jobs:
           export DOCKER_CLI_EXPERIMENTAL=enabled
 
           function validate_image() {
-                  local image=${1}
-                  if [[ "$VCN_SIGNER" =~ ^0x ]]; then
-                    local vcn_cli=("--signerID")
-                  else
-                    local vcn_cli=("--org")
-                  fi
+            local image=${1}
+            if [[ "$VCN_SIGNER" =~ ^0x ]]; then
+              local vcn_cli=("--signerID")
+            else
+              local vcn_cli=("--org")
+            fi
 
-                  state="$(vcn authenticate "$vcn_cli" "$VCN_SIGNER" --output json docker://"${image}" | jq '.verification.status // 2')"
+            state="$(vcn authenticate "$vcn_cli" "$VCN_SIGNER" --output json docker://"${image}" | jq '.verification.status // 2')"
 
-                  echo "${state}"
+            if [[ "${state}" != "0" ]]; then
+              echo "Invalid signature!"
+              exit 1
+            fi
 
-                  if [[ "${state}" != "0" ]]; then
-                          echo "Invalid signature!"
-                          exit 1
-                  fi
           }
 
           for docker_reg in "drypatrick" "ghcr.io/drypatrick"; do
