Update validate-images.yml

diff --git a/.github/workflows/validate-images.yml b/.github/workflows/validate-images.yml
--- a/.github/workflows/validate-images.yml
+++ b/.github/workflows/validate-images.yml
@@ -75,23 +75,23 @@ jobs:
           export DOCKER_CLI_EXPERIMENTAL=enabled
 
           function validate_image() {
-            local image=${1}
-            
-            if [[ "$VCN_ORG" =~ ^0x ]]; then
-              vcn_cli=("--signerID" "$VCN_ORG")
-            else
-              vcn_cli=("--org" "$VCN_ORG") 
-            fi
-            
-            echo "${vcn_cli}"
-            echo "vcn authenticate "${vcn_cli}" --output json docker://${image}"
-            
-            state="$(vcn authenticate ${vcn_cli} $VCN_ORG--output json docker://"${image}" | jq '.verification.status // 2')"
-            
-            if [[ "${state}" != "0" ]]; then
-              echo "Invalid signature!"
-              exit 1
-            fi
+                  local image=${1}
+                  
+                  if [[ "$VCN_ORG" =~ ^0x ]]; then
+                          vcn_cli="--signerID"
+                  else
+                          vcn_cli="--org" 
+                  fi
+
+                  echo "${vcn_cli}"
+                  echo "vcn authenticate ${vcn_cli} $VCN_ORG --output json docker://${image}"
+                  
+                  state="$(vcn authenticate ${vcn_cli} $VCN_ORG --output json docker://"${image}" | jq '.verification.status // 2')"
+                  
+                  if [[ "${state}" != "0" ]]; then
+                          echo "Invalid signature!"
+                          exit 1
+                  fi
           }
 
           for docker_reg in "drypatrick" "ghcr.io/drypatrick"; do
